using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CodeGeneration
{
    class Program
    {
        static void Main(string[] args)
        {
            var currentDirectory = new DirectoryInfo(Environment.CurrentDirectory);
            var solutionDirectory = currentDirectory.Parent.Parent.Parent;
            if (!solutionDirectory.EnumerateFiles().Any(f => f.Name == "MedallionCodeFormatter.sln"))
            {
                throw new InvalidOperationException("Could not find solution file in " + solutionDirectory.FullName);
            }

            var incrementalRewriterPath = Path.Combine(solutionDirectory.FullName, "MedallionCodeFormatter", "CSharpSyntaxIncrementalRewriter.Autogenerated.cs");
            using (var writer = new StreamWriter(incrementalRewriterPath))
            {
                new CSharpSyntaxIncrementalRewriterGenerator(writer).Generate();
            }

            Console.ReadKey();
        }
    }
}
